node.js版の更新
  * Babel7

Node.js8、Python2.7じゃないと？ `npm install` に失敗する。

Webpackに成功するが、実行すると落ちる。

```sh
$ node nesemu.js ~/apps/emu/rom/nes/Super\ Mario\ Bros.\ \(Japan,\ USA\).zip
/Users/admin/repos/github/nesemu/nodejs/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /Users/admin/repos/github/nesemu/nodejs/node_modules/ffi/build/ffi_bindings.node
 → /Users/admin/repos/github/nesemu/nodejs/node_modules/ffi/build/Debug/ffi_bindings.node
 → /Users/admin/repos/github/nesemu/nodejs/node_modules/ffi/build/Release/ffi_bindings.node
 → /Users/admin/repos/github/nesemu/nodejs/node_modules/ffi/out/Debug/ffi_bindings.node
 → /Users/admin/repos/github/nesemu/nodejs/node_modules/ffi/Debug/ffi_bindings.node
 → /Users/admin/repos/github/nesemu/nodejs/node_modules/ffi/out/Release/ffi_bindings.node
 → /Users/admin/repos/github/nesemu/nodejs/node_modules/ffi/Release/ffi_bindings.node
 → /Users/admin/repos/github/nesemu/nodejs/node_modules/ffi/build/default/ffi_bindings.node
 → /Users/admin/repos/github/nesemu/nodejs/node_modules/ffi/compiled/11.1.0/darwin/x64/ffi_bindings.node
    at bindings (/Users/admin/repos/github/nesemu/nodejs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/Users/admin/repos/github/nesemu/nodejs/node_modules/ffi/lib/bindings.js:2:37)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/admin/repos/github/nesemu/nodejs/node_modules/ffi/lib/ffi.js:10:16)
```